### ISSUE TITLE
Android Crashing When Attempting Logout

### ISSUE THREAD

**Issue by edwinduong** [ParkWithEase/parkeasy#194]
I encountered this bug while developing the ProfileScreen for the Android app where the app just crashes when an attempt to logout is made. I'm unsure of how to reproduce the bug, but the problem seems to go away after doing a fresh install of the app.

Error Output 1:
```
16:39:02.192  E  FATAL EXCEPTION: main
                 Process: io.github.parkwithease.parkeasy, PID: 7021
                 java.util.NoSuchElementException: Collection contains no element matching the predicate.
                 	at io.ktor.http.CookieKt.parseServerSetCookieHeader(Cookie.kt:230)
                 	at io.github.parkwithease.parkeasy.data.local.AuthRepositoryImpl$special$$inlined$map$1$2.emit(Emitters.kt:224)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
                 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
                 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
                 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                 	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
                 	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
                 	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
                 	at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1689)
                 	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:642)
                 	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
                 	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
                 	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:3089)
                 	at kotlinx.coroutines.channels.BufferedChannel.send(Unknown Source:0)
                 	at kotlinx.coroutines.channels.ChannelCoroutine.send(Unknown Source:2)
                 	at androidx.datastore.core.DataStoreImpl$data$1$3.emit(DataStoreImpl.kt:160)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
                 	at androidx.datastore.core.DataStoreImpl$internalDataFlow$1.invokeSuspend(DataStoreImpl.kt:125)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at android.os.Handler.handleCallback(Handler.java:959)
                 	at android.os.Handler.dispatchMessage(Handler.java:100)
                 	at android.os.Looper.loopOnce(Looper.java:232)
                 	at android.os.Looper.loop(Looper.java:317)
                 	at android.app.ActivityThread.main(ActivityThread.java:8705)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8cb4b, Dispatchers.Main.immediate]
```

Error Output 2:
```
16:52:21.067  E  FATAL EXCEPTION: main
                 Process: io.github.parkwithease.parkeasy, PID: 7389
                 java.util.NoSuchElementException: Collection contains no element matching the predicate.
                 	at io.ktor.http.CookieKt.parseServerSetCookieHeader(Cookie.kt:230)
                 	at io.github.parkwithease.parkeasy.data.local.AuthRepositoryImpl$special$$inlined$map$1$2.emit(Emitters.kt:224)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                 	at io.github.parkwithease.parkeasy.ui.profile.ProfileViewModel.onLogoutPress(ProfileViewModel.kt:17)
                 	at io.github.parkwithease.parkeasy.ui.profile.ProfileScreenKt$ProfileScreen$2.invoke$lambda$2$lambda$1$lambda$0(ProfileScreen.kt:37)
                 	at io.github.parkwithease.parkeasy.ui.profile.ProfileScreenKt$ProfileScreen$2.$r8$lambda$PnCxCizkBAxuapkKnyAwT6JbLM8(Unknown Source:0)
                 	at io.github.parkwithease.parkeasy.ui.profile.ProfileScreenKt$ProfileScreen$2$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke-k-4lQ0M(Clickable.kt:639)
                 	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:633)
                 	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
                 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:719)
                 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:598)
                 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:620)
                 	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1044)
                 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:387)
                 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
                 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:373)
                 	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:229)
                 	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:144)
                 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:120)
                 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1994)
                 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1945)
16:52:21.070  E  	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1829)
                 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:458)
                 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
                 	at android.app.Activity.dispatchTouchEvent(Activity.java:4533)
                 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:416)
                 	at android.view.View.dispatchPointerEvent(View.java:16729)
                 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7947)
                 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7710)
                 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7106)
                 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
                 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
                 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7295)
                 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
                 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7352)
                 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
                 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
                 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
                 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
                 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
                 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10214)
                 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10165)
                 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10134)
                 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10356)
                 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
                 	at android.os.MessageQueue.nativePollOnce(Native Method)
                 	at android.os.MessageQueue.next(MessageQueue.java:346)
                 	at android.os.Looper.loopOnce(Looper.java:189)
                 	at android.os.Looper.loop(Looper.java:317)
                 	at android.app.ActivityThread.main(ActivityThread.java:8705)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@29f68d6, androidx.compose.runtime.BroadcastFrameClock@b550757, StandaloneCoroutine{Cancelling}@fbad244, AndroidUiDispatcher@3346f2d]
```

**Comment by edwinduong** [comment]
Bug found and fixed, `parseServerSetCookieHeader` was unable to parse the session cookie since `AuthRepositoryImpl::reset` only set `preferences[session] = ""`

Fix: offending code now properly *removes* the session cookie altogether instead of replacing with an empty string, and proper error checks are now in place to combat null and NoSuchElementExceptions
